#@ load("@ytt:data", "data")

#@ for app in data.values.apps:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ app.name
  labels:
    app: #@ app.name
    type: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ app.name
      type: user-app
  template:
    metadata:
      labels:
        app: #@ app.name
        type: user-app
    spec:
      containers:
        - name: #@ app.name
          #@ if app.name == 'tracing-server':
          image: openzipkin/zipkin
          #@ else:
          image: #@ "showpune/spring-petclinic-"+ str(app.name) + "-noeureka:3.0.2"
          #@ end
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          ports:
            - name: app-port
              containerPort: #@ app.port
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server"
            - name: CONSOLE_LOG_THRESHOLD
              value: "ALL"
#@ end

#@ for app in data.values.apps:
---
apiVersion: v1
kind: Service
metadata:
  name: #@ app.name
spec:
  selector:
    app: #@ app.name
  ports:
    - protocol: TCP
      port: 80
      targetPort: app-port
  type: #@ app.serviceType
#@ end
